"""Add slug field to pet_categories and pets

Revision ID: 28590b0ffbd5
Revises: 99a4664d0756
Create Date: 2025-06-27 07:28:30.313349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28590b0ffbd5'
down_revision: Union[str, Sequence[str], None] = '99a4664d0756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_categories', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'pet_categories', ['slug'])
    op.add_column('pets', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'pets', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='unique')
    op.drop_column('pets', 'slug')
    op.drop_constraint(None, 'pet_categories', type_='unique')
    op.drop_column('pet_categories', 'slug')
    # ### end Alembic commands ###
