version: '3.8'

services:
  web:
    build: app
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: sergei
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: db_for_web_shop

  seed:
    build: app
    command: >
      sh -c "sleep 5 && 
      psql -h db -U sergei -d db_for_web_shop -f /app/db_init/seed_data.sql"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: