name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: sergei
          POSTGRES_PASSWORD: admin1234
          POSTGRES_DB: db_for_web_shop
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          for i in $(seq 1 10); do
            pg_isready -h localhost -p 5432 && exit 0
            echo "Waiting for postgres... ($i/10)"
            sleep 2
          done
          echo "Postgres is not ready after 10 attempts."
          exit 1
          
      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://sergei:admin1234@localhost:5432/db_for_web_shop
        run: |
          pytest --maxfail=1 --disable-warnings -q

